package com.everis.equipo2.proyecto.semana2.inventario.model;
// Generated 18/09/2019 12:15:01 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Compra generated by hbm2java
 */
@Entity
@Table(name = "compra", catalog = "inventario")
public class Compra implements java.io.Serializable {

	private Integer idcompra;
	private Date fechacompra;
	private Set<ProductoCompra> productoCompras = new HashSet<ProductoCompra>(0);

	public Compra() {
	}

	public Compra(Date fechacompra) {
		this.fechacompra = fechacompra;
	}

	public Compra(Date fechacompra, Set<ProductoCompra> productoCompras) {
		this.fechacompra = fechacompra;
		this.productoCompras = productoCompras;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idcompra", unique = true, nullable = false)
	public Integer getIdcompra() {
		return this.idcompra;
	}

	public void setIdcompra(Integer idcompra) {
		this.idcompra = idcompra;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechacompra", nullable = false, length = 19)
	public Date getFechacompra() {
		return this.fechacompra;
	}

	public void setFechacompra(Date fechacompra) {
		this.fechacompra = fechacompra;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "compra")
	public Set<ProductoCompra> getProductoCompras() {
		return this.productoCompras;
	}

	public void setProductoCompras(Set<ProductoCompra> productoCompras) {
		this.productoCompras = productoCompras;
	}

}
