package com.everis.equipo2.proyecto.semana2.inventario.model;
// Generated 18/09/2019 12:15:01 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * ProductoVenta generated by hbm2java
 */
@Entity
@Table(name = "producto_venta", catalog = "inventario")
public class ProductoVenta implements java.io.Serializable {

	private Integer idProductoVenta;
	@JsonIgnore
	private Producto producto;
	@JsonIgnore
	private Venta venta;
	private int cantidad;

	public ProductoVenta() {
	}

	public ProductoVenta(Producto producto, Venta venta, int cantidad) {
		this.producto = producto;
		this.venta = venta;
		this.cantidad = cantidad;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_producto_venta", unique = true, nullable = false)
	public Integer getIdProductoVenta() {
		return this.idProductoVenta;
	}

	public void setIdProductoVenta(Integer idProductoVenta) {
		this.idProductoVenta = idProductoVenta;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "producto_idproducto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "venta_idventa", nullable = false)
	public Venta getVenta() {
		return this.venta;
	}

	public void setVenta(Venta venta) {
		this.venta = venta;
	}

	@Column(name = "cantidad", nullable = false)
	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

}
