package com.everis.equipo2.proyecto.semana2.inventario.model;
// Generated 18/09/2019 12:15:01 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * ProductoCompra generated by hbm2java
 */
@Entity
@Table(name = "producto_compra", catalog = "inventario")
public class ProductoCompra implements java.io.Serializable {

	private Integer idProductoCompra;
    @JsonIgnore
	private Compra compra;
    @JsonIgnore
	private Producto producto;
	private int cantidad;

	public ProductoCompra() {
	}

	public ProductoCompra(Compra compra, Producto producto, int cantidad) {
		this.compra = compra;
		this.producto = producto;
		this.cantidad = cantidad;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_producto_compra", unique = true, nullable = false)
	public Integer getIdProductoCompra() {
		return this.idProductoCompra;
	}

	public void setIdProductoCompra(Integer idProductoCompra) {
		this.idProductoCompra = idProductoCompra;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "compra_idcompra", nullable = false)
	public Compra getCompra() {
		return this.compra;
	}

	public void setCompra(Compra compra) {
		this.compra = compra;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "producto_idproducto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "cantidad", nullable = false)
	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

}
