package com.everis.equipo2.proyecto.semana2.inventario.model;
// Generated 18/09/2019 12:15:01 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Venta generated by hbm2java
 */
@Entity
@Table(name = "venta", catalog = "inventario")
public class Venta implements java.io.Serializable {

	private Integer idventa;
	private Date fechaventa;
	private Set<ProductoVenta> productoVentas = new HashSet<ProductoVenta>(0);

	public Venta() {
	}

	public Venta(Date fechaventa) {
		this.fechaventa = fechaventa;
	}

	public Venta(Date fechaventa, Set<ProductoVenta> productoVentas) {
		this.fechaventa = fechaventa;
		this.productoVentas = productoVentas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idventa", unique = true, nullable = false)
	public Integer getIdventa() {
		return this.idventa;
	}

	public void setIdventa(Integer idventa) {
		this.idventa = idventa;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaventa", nullable = false, length = 19)
	public Date getFechaventa() {
		return this.fechaventa;
	}

	public void setFechaventa(Date fechaventa) {
		this.fechaventa = fechaventa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "venta")
	public Set<ProductoVenta> getProductoVentas() {
		return this.productoVentas;
	}

	public void setProductoVentas(Set<ProductoVenta> productoVentas) {
		this.productoVentas = productoVentas;
	}

}
